//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPProject.DataBaseModel {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class serialize_config : global::System.Configuration.ApplicationSettingsBase {
        
        private static serialize_config defaultInstance = ((serialize_config)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new serialize_config())));
        
        public static serialize_config Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./DBSerializedCollection/users")]
        public string SerializeUserCollectionPath {
            get {
                return ((string)(this["SerializeUserCollectionPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./DBSerializedCollection/blocked_users")]
        public string SerializeBlockedUserCollectionPath {
            get {
                return ((string)(this["SerializeBlockedUserCollectionPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./DBSerializedCollection/films")]
        public string SerializeFilmCollectionPath {
            get {
                return ((string)(this["SerializeFilmCollectionPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./DBSerializedCollection/sessions")]
        public string SerializeSessionCollectionPath {
            get {
                return ((string)(this["SerializeSessionCollectionPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./DBSerializedCollection/tickets")]
        public string SerializeTicketCollectionPath {
            get {
                return ((string)(this["SerializeTicketCollectionPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./DBSerializedCollection/reviews")]
        public string SerializeReviewCollectionPath {
            get {
                return ((string)(this["SerializeReviewCollectionPath"]));
            }
        }
    }
}
